markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "恒阅读书会"
markdown: rdiscount

author: "伊迭"
atom-baseurl: "http://HengYueDuShuHui.com"
disqus: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

