markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "恒阅读书会"
markdown: rdiscount

author: "伊迭"
atom-baseurl: "http://HengYueDuShuHui.com"
disqus: ""

navigations:
  - title: 存档
    class: fa fa-list-ul
    href: /archive.html
  - title: 标签
    class: fa fa-tags
    href: /tags.html
  - title: 关于
    class: fa fa-user
    href: /about.html
  - title: 订阅
    class: fa fa-rss
    href: /atom.xml

